CREATE TABLE MEMBER_INFO(
    ID VARCHAR2(300) CONSTRAINT PK_MEMBER PRIMARY KEY,
    PASSWORD VARCHAR2(300) NULL,
    ENABLED INTEGER NULL, 
    FIRST_NAME VARCHAR2(30) NOT NULL,
    LAST_NAME VARCHAR2(30) NOT NULL,
    MEMBER_CLASS NUMBER NOT NULL,
    JOIN_DATE DATE NOT NULL,
    USE_DATE DATE NOT NULL,
    INTRO VARCHAR2(4000),
    COUNTRY VARCHAR2(100),
    GENDER VARCHAR2(6),
    BIRTHDAY VARCHAR2(30),
    EMAIL VARCHAR2(4000) UNIQUE,
    TELEPHONE VARCHAR2(11),
    LOGIN_TYPE NUMBER
);

CREATE TABLE MEMBER_AUTHORITY(
	ID VARCHAR2(30) CONSTRAINT PK_MEMBER_AUTHORITY PRIMARY KEY,
	AUTHORITY VARCHAR2(50) NOT NULL
);

CREATE TABLE BOARD(
    BOARD_NO NUMBER(3) CONSTRAINT PK_BOARD PRIMARY KEY,
    ID VARCHAR2(300) NOT NULL,
    TITLE VARCHAR2(4000) NOT NULL,
    BOARD_TYPE NUMBER(2) NOT NULL,
    BOARD_CONTENT VARCHAR2(4000) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    TOUR_TIME NUMBER,
    REGION VARCHAR2(20) NOT NULL,
    BUDGET NUMBER,
    COMPANY NUMBER,
    WRITE_DATE DATE NOT NULL,
    READ_COUNT NUMBER NOT NULL,
    PHOTO_PATH VARCHAR2(4000),
    CONSTRAINT FK_BOARD FOREIGN KEY(ID) REFERENCES MEMBER_INFO(ID) ON DELETE CASCADE
);
CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1 START WITH 1;

CREATE TABLE MY_COMMENT(
    COMMENT_NO NUMBER CONSTRAINT PK_COMMENT PRIMARY KEY,
    EMAIL VARCHAR2(4000) NOT NULL ,
    BOARD_NO NUMBER NOT NULL,
    BOARD_TYPE VARCHAR2(15) NOT NULL,
    COMMENT_CONTENT VARCHAR2(4000) NOT NULL,
    COMMENT_DATE DATE NOT NULL,
    REFER NUMBER(3) NOT NULL,
    LEV NUMBER(3) NOT NULL,
    STEP NUMBER(3) NOT NULL,
    CONSTRAINT FK_COMMENT_EMAIL FOREIGN KEY(EMAIL) REFERENCES MEMBER_INFO(EMAIL) ON DELETE CASCADE
);
CREATE SEQUENCE MY_COMMENT_SEQ INCREMENT BY 1 START WITH 1;

CREATE TABLE TOUR_DIARY(
    DIARY_NO NUMBER(4) CONSTRAINT PK_TOUR_DIARY PRIMARY KEY,
    EMAIL VARCHAR2(60) NOT NULL ,
    TITLE VARCHAR2(50) NOT NULL,
    REGION VARCHAR2(20) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    DIARY_CONTENT VARCHAR2(4000) NOT NULL,
    COMPANY VARCHAR2(60) NOT NULL,
    WRITE_DATE DATE NOT NULL,
    COUNT_READ NUMBER(3) NOT NULL,
    USER_LIKE NUMBER(3),
    CONSTRAINT FK_TOUR_DIARY_EMAIL FOREIGN KEY(EMAIL) REFERENCES MEMBER_INFO(EMAIL) ON DELETE CASCADE,
    CONSTRAINT FK_TOUR_DIARY_COMPANY FOREIGN KEY(COMPANY) REFERENCES MEMBER_INFO(EMAIL) ON DELETE CASCADE
);
CREATE SEQUENCE TOUR_DIARY_SEQ INCREMENT BY 1 START WITH 1;

create table notice(
NOTICE_NO NUMBER(11) CONSTRAINT NOTICE_NO_PK PRIMARY KEY,
ADMIN_ID VARCHAR2(40),
TITLE VARCHAR2(30),
CONTENT VARCHAR2(400),
POSTDATE DATE,
CONSTRAINT ADMIN_ID_FK FOREIGN KEY(ADMIN_ID) REFERENCES MEMBER_INFO(ID) ON DELETE CASCADE
);
CREATE SEQUENCE NOTICE_NO_SEQ INCREMENT BY 1 START WITH 1;

create table location(
BOARD_NO NUMBER(3) NOT NULL,
LOCATION_JB NUMBER NOT NULL,
LOCATION_IB NUMBER NOT NULL,
CONSTRAINT BOARD_NO_FK FOREIGN KEY(BOARD_NO) REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE
);

create table chating(
CHATING_ROOM NUMBER NOT NULL,
CHATING_MEMBER1 VARCHAR2(4000) NOT NULL,
CHATING_MEMBER2 VARCHAR2(4000) NOT NULL,
CHATING_CONTENT VARCHAR2(4000)
);
CREATE SEQUENCE CHATING_ROOM_SEQ INCREMENT BY 1 START WITH 1;

CREATE TABLE PHOTO(
    EMAIL VARCHAR2(300) ,
    PHOTO_PATH VARCHAR2(4000) NOT NULL
);

select * from tab;