
DROP TABLE MY_COMMENT;
DROP SEQUENCE MY_COMMENT_SEQ;

DROP TABLE PHOTO;
DROP SEQUENCE PHOTO_SEQ;

DROP TABLE TOUR_DIARY;
DROP SEQUENCE TOUR_DIARY_SEQ;

DROP TABLE FAVORITE;
DROP SEQUENCE FAVORITE_SEQ;

drop table notice;
drop table administrate;
drop table chat;
drop table chating_room;

drop sequence CHATING_ID_SEQ;
drop sequence MESSAGE_ID_SEQ;
drop sequence NOTICE_NO_SEQ;

DROP TABLE LOCATION;

DROP TABLE BOARD;
DROP SEQUENCE BOARD_SEQ;

DROP TABLE MEMBER_AUTHORITY;

DROP TABLE MEMBER_INFO;

DROP TABLE CHATING;

DROP SEQUENCE CHATING_ROOM_SEQ;

purge recyclebin;
